# Generated by Django 4.1.7 on 2023-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadCsv', '0002_remove_userprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
